modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="pale_forest"
version="1.0.0"
displayName="Mackery's Winter Drop"
displayURL="https://mcreator.net"
credits="Mackery Mackery Mackery"
authors="Mackery"
description="Mackery's Version of the Winter Drop"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pale_forest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration